// ============================================
// TEST DATA
// ============================================

const validationTests = [
  {
    test: "id required (missing)",
    payload: {
      title: "Valid Title",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "id unique (duplicate)",
    payload: {
      id: "book-001",
      title: "Title1",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 409,
  },
  {
    test: "id minlength (empty string)",
    payload: {
      id: "",
      title: "Title",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "id maxlength (too long)",
    payload: {
      id: "a".repeat(51),
      title: "Title",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "id match (invalid chars)",
    payload: {
      id: "invalid id!",
      title: "Title",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "title required (missing)",
    payload: {
      id: "id1",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "title minlength (empty string)",
    payload: {
      id: "id1",
      title: "",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "title maxlength (too long)",
    payload: {
      id: "id1",
      title: "a".repeat(201),
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "title match (invalid chars)",
    payload: {
      id: "id1",
      title: "Invalid@Title#",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "author required (missing)",
    payload: {
      id: "id2",
      title: "Title",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "author minlength (too short)",
    payload: {
      id: "id2",
      title: "Title",
      author: "A",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "author maxlength (too long)",
    payload: {
      id: "id2",
      title: "Title",
      author: "a".repeat(101),
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "author match (invalid chars)",
    payload: {
      id: "id2",
      title: "Title",
      author: "Author123!",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "year required (missing)",
    payload: {
      id: "id3",
      title: "Title",
      author: "Author",
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "year min (too small)",
    payload: {
      id: "id3",
      title: "Title",
      author: "Author",
      year: 999,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "year max (too large)",
    payload: {
      id: "id3",
      title: "Title",
      author: "Author",
      year: new Date().getFullYear() + 6,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "year integer check (decimal)",
    payload: {
      id: "id3",
      title: "Title",
      author: "Author",
      year: 2000.5,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "genre required (missing)",
    payload: {
      id: "id4",
      title: "Title",
      author: "Author",
      year: 2000,
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "genre enum (invalid value)",
    payload: {
      id: "id4",
      title: "Title",
      author: "Author",
      year: 2000,
      genre: "InvalidGenre",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "summary required (missing)",
    payload: {
      id: "id5",
      title: "Title",
      author: "Author",
      year: 2000,
      genre: "Other",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "summary minlength (too short)",
    payload: {
      id: "id5",
      title: "Title",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "short",
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "summary maxlength (too long)",
    payload: {
      id: "id5",
      title: "Title",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "a".repeat(2001),
      price: "10.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "price required (missing)",
    payload: {
      id: "id6",
      title: "Title",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "price min (negative)",
    payload: {
      id: "id6",
      title: "Title",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "-1.00",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "extra field (strict mode)",
    payload: {
      id: "id8",
      title: "Title",
      author: "Author",
      year: 2000,
      genre: "Other",
      summary: "Valid summary text",
      price: "10.00",
      currency: "AUD",
      extraField: "not allowed",
    },
    expectedStatus: 400,
  },
];

const putValidationTests = [
  {
    test: "PUT - Update book successfully",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "Updated Author",
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 200,
  },
  {
    test: "PUT - Book not found",
    id: "non-existent-book-id",
    payload: {
      title: "Updated Title",
      author: "Updated Author",
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 404,
  },
  {
    test: "PUT - Title validation (empty)",
    id: "book-001",
    payload: {
      title: "",
      author: "Updated Author",
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Title validation (too long)",
    id: "book-001",
    payload: {
      title: "a".repeat(201),
      author: "Updated Author",
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Title validation (invalid chars)",
    id: "book-001",
    payload: {
      title: "Invalid@Title#123",
      author: "Updated Author",
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Author validation (empty)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "",
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Author validation (too short)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "A",
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Author validation (too long)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "a".repeat(101),
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Author validation (invalid chars)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "Author123!@#",
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Year validation (too small)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "Updated Author",
      year: 999,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Year validation (too large)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "Updated Author",
      year: new Date().getFullYear() + 6,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Year validation (decimal)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "Updated Author",
      year: 2021.5,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Genre validation (invalid enum)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "Updated Author",
      year: 2021,
      genre: "InvalidGenre",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Summary validation (too short)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "Updated Author",
      year: 2021,
      genre: "Fiction",
      summary: "short",
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Summary validation (too long)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "Updated Author",
      year: 2021,
      genre: "Fiction",
      summary: "a".repeat(2001),
      price: "15.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Price validation (negative)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "Updated Author",
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "-5.99",
      currency: "AUD",
    },
    expectedStatus: 400,
  },
  {
    test: "PUT - Price validation (zero)",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "Updated Author",
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "0.00",
      currency: "AUD",
    },
    expectedStatus: 200,
  },
  {
    test: "PUT - Extra field in payload",
    id: "book-001",
    payload: {
      title: "Updated Title",
      author: "Updated Author",
      year: 2021,
      genre: "Fiction",
      summary: "Updated summary text for the book",
      price: "15.99",
      currency: "AUD",
      extraField: "not allowed",
    },
    expectedStatus: 400,
  },
];

module.exports = {
  validationTests,
  putValidationTests,
};
